%YAML:1.0

data_path: /home/cm/dataset/data_qinghuamen
image_list: - IMG_5589.jpg
            - IMG_5590.jpg
            - IMG_5591.jpg
            # - IMG_5592.jpg
            # - IMG_5593.jpg
            # - IMG_5594.jpg
            # - IMG_5595.jpg
            # - IMG_5596.jpg
            # - IMG_5597.jpg
            # - IMG_5598.jpg
            # - IMG_5599.jpg
            # - IMG_5600.jpg
            # - IMG_5601.jpg
            # - IMG_5603.jpg
            # - IMG_5605.jpg
            # - IMG_5610.jpg
            # - IMG_5611.jpg
            # - IMG_5612.jpg
            # - IMG_5613.jpg
            # - IMG_5614.jpg
            # - IMG_5615.jpg
            # - IMG_5616.jpg
            # - IMG_5617.jpg
            # - IMG_5618.jpg
            # - IMG_5619.jpg
            # - IMG_5620.jpg
            # - IMG_5621.jpg
            # - IMG_5622.jpg
            # - IMG_5623.jpg
            # - IMG_5624.jpg
            # - IMG_5625.jpg
            # - IMG_5626.jpg
            # - IMG_5630.jpg
            # - IMG_5633.jpg
            # - IMG_5634.jpg
            # - IMG_5635.jpg
            # - IMG_5636.jpg
            # - IMG_5637.jpg
            # - IMG_5638.jpg
            # - IMG_5639.jpg
            # - IMG_5640.jpg
            # - IMG_5641.jpg
            # - IMG_5642.jpg
            # - IMG_5645.jpg
            # - IMG_5646.jpg
            # - IMG_5647.jpg
            # - IMG_5648.jpg
            # - IMG_5650.jpg
            # - IMG_5652.jpg
            # - IMG_5653.jpg
            # - IMG_5654.jpg
            # - IMG_5655.jpg
            # - IMG_5656.jpg
            # - IMG_5657.jpg
            # - IMG_5658.jpg
            # - IMG_5660.jpg